### PR TITLE
Added validation around cicsplex and region for SMSS support

### PR DESCRIPTION
**Pull request by ledina**

### CODE REVIEW

**Comment by sophiegreen** [comment]
Wondering if this logic should be in BundleDeployHelper in cics-bundle-common so that it's covered for both Maven and Gradle?

**Comment by ledina** [comment]
> Wondering if this logic should be in BundleDeployHelper in cics-bundle-common so that it's covered for both Maven and Gradle?

All the rest of the validation and corresponding testing is currently in the separate repos, so I thought it made sense to keep it consistent.

**Comment by sophiegreen** [comment]
Yep you're right actually! Although I also just found this pull request where we chose to move the validation of cicsplex and region into the server.... https://github.com/IBM/cics-bundle-maven/pull/161/files

**Comment by ledina** [comment]
Yes that is right, and that is because we don't know if it will be a plex or SMSS region, hence we let the server deal with that side of things, but we know we need either both or none of them to be specified, so we are choosing to report that early on.

**Comment by sophiegreen** [comment]
That makes sense, I think this looks good then. And we'll need the same added to the maven plugin, because it doesn't look like we're validating it there either.

**Review by sophiegreen — APPROVED** [review]

**Comment by ledina** [comment]
Yep, maven is next!

**Pull request merged**
