### PR TITLE
update version number to 0.0.3-SNAPSHOT

### PR DESCRIPTION
**Pull request by vera-chan**
Signed-off-by: Vera <vera.xx.c@me.com>

### CODE REVIEW

**Comment by ind1go** [comment]
Hi Vera! We like to leave the README with the most recent release version, as that's the golden path - users only need the snapshot if they're trying out the latest-and-greatest nightly build for an as-yet-unreleased feature.

**Comment by tom-foyle** [comment]
> Hi Vera! We like to leave the README with the most recent release version, as that's the golden path - users only need the snapshot if they're trying out the latest-and-greatest nightly build for an as-yet-unreleased feature.

The reason this came up is that the README currently talks about 0.0.3-SNAPSHOT features, crucially 'cicsBundlePart' rather than the older 'cicsBundle' config, but the version number mentioned is 0.0.2, so anybody following it will end up with a bundle that won't work. I guess you're saying we should have left the README at 0.0.2 level and only updated it with the info on 'cicsBundlePart' after we had released 0.0.3. Perhaps the best thing to do here is to just release 0.0.3 now?

**Comment by ind1go** [comment]
> Perhaps the best thing to do here is to just release 0.0.3 now?

I think I'd agree!

**Comment by ledina** [comment]
Superseded by 1.0.0 release. Closing.

**Pull request closed without merging**
